[package]
name = "screenshot_project"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
scrap = "0.5.0"
image = "0.24.7"
imageproc = "0.23.0"